<?php

/**
 * Единый конфиг стран для импорта со старого сайта (past.bsigroup.ru).
 *
 * Используется обоими сущностями сразу — экскурсии (t_excursions) и
 * достопримечательности (t_sights) — через tools/legacy-import/export.php.
 * Раньше конфиг был продублирован в tools/legacy-excursions/export.php и
 * tools/legacy-sights/export.php; здесь они слиты, карты городов объединены.
 *
 * Поля:
 *   legacy_id            — ID страны в t_countries старого сайта;
 *   country_slug         — слаг записи CPT country в WordPress;
 *   default_region       — регион для городов, которых нет в `cities`;
 *   cities               — имя города => имя региона,
 *                          либо ['region' => …, 'resort' => …|null]
 *                          (resort => null: город не превращать в курорт);
 *   subtype_regions      — запасная раскладка по S_SUBTYPE (историческая область),
 *                          для записей без города;
 *   ignore_cities        — мусор источника: город вычищается;
 *   skip_title_patterns  — регулярки отсева не-экскурсий (бухгалтерия заявок).
 *
 * Если города нет ни в `cities`, ни в `subtype_regions`, экспорт подставляет
 * регион из t_cities.C_SUBTYPE (историческая область старого сайта). Не нашлось
 * и там — запись уходит без региона, только с курортом.
 */

declare(strict_types=1);

return [
  'are' => [
    'legacy_id' => 2,
    'country_slug' => 'oae',
    'default_region' => null,
    'cities' => [
      'Дубай' => 'Дубай',
      'Абу-Даби' => 'Абу-Даби',
    ],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [
      '/по программе/iu',
    ],
  ],
  'arm' => [
    'legacy_id' => 3741,
    'country_slug' => 'armeniya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'aut' => [
    'legacy_id' => 90,
    'country_slug' => 'avstriya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'aze' => [
    'legacy_id' => 48963303,
    'country_slug' => 'azerbajdzhan',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'bel' => [
    'legacy_id' => 3,
    'country_slug' => 'belgiya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'blr' => [
    'legacy_id' => 375,
    'country_slug' => 'belorussiya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'che' => [
    'legacy_id' => 76,
    'country_slug' => 'shvejczariya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'chn' => [
    'legacy_id' => 34,
    'country_slug' => 'kitaj',
    'default_region' => null,
    'cities' => [
      'Пекин' => 'Северный Китай',
      'Пинъяо' => 'Северный Китай',
      'Шанхай' => 'Восточный Китай',
      'Ханчжоу' => 'Восточный Китай',
      'Сучжоу' => 'Восточный Китай',
      'Лоян' => 'Центральный Китай',
      'Сиань' => 'Северо-Запад Китая',
      'Лхаса' => 'Юго-Запад Китая',
      'Шигадзе' => 'Юго-Запад Китая',
      'Сага' => 'Юго-Запад Китая',
      'Чэнду' => 'Юго-Запад Китая',
      'Лешань' => 'Юго-Запад Китая',
      'Куньмин' => 'Юго-Запад Китая',
      'Лицзян' => 'Юго-Запад Китая',
      'Гуйлинь' => 'Южный Китай',
      'Макао' => 'Южный Китай',
      'Гонконг' => 'Гонконг',
      'Харбин' => 'Северо-Восток Китая',
      'Аньшань' => 'Северо-Восток Китая',
      'Хуньчунь' => 'Северо-Восток Китая',
      'о. Хайнань' => [
        'region' => 'Остров Хайнань',
        'resort' => null,
      ],
      'По программе' => [
        'region' => null,
        'resort' => null,
      ],
    ],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'cyp' => [
    'legacy_id' => 10,
    'country_slug' => 'kipr',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'cze' => [
    'legacy_id' => 15,
    'country_slug' => 'chehiya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'deu' => [
    'legacy_id' => 40,
    'country_slug' => 'germaniya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'esp' => [
    'legacy_id' => 84,
    'country_slug' => 'ispaniya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'fin' => [
    'legacy_id' => 64,
    'country_slug' => 'finlyandiya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'fra' => [
    'legacy_id' => 30,
    'country_slug' => 'francziya',
    'default_region' => null,
    'cities' => [
      'Париж' => 'Иль-де-Франс',
      'Шантийи' => 'О-де-Франс',
      'Лилль' => 'О-де-Франс',
      'Авиньон' => 'Прованс – Альпы – Лазурный Берег',
      'Ницца' => 'Прованс – Альпы – Лазурный Берег',
      'Марсель' => 'Прованс – Альпы – Лазурный Берег',
      'Экс-ан-Прованс' => 'Прованс – Альпы – Лазурный Берег',
      'Канны' => 'Прованс – Альпы – Лазурный Берег',
      'Грасс' => 'Прованс – Альпы – Лазурный Берег',
      'Арль' => 'Прованс – Альпы – Лазурный Берег',
      'Горд' => 'Прованс – Альпы – Лазурный Берег',
      'Ле Бо де Прованс' => 'Прованс – Альпы – Лазурный Берег',
      'Сен-Тропе' => 'Прованс – Альпы – Лазурный Берег',
      'Жуан-ле-Пен' => 'Прованс – Альпы – Лазурный Берег',
      'Монако' => 'Прованс – Альпы – Лазурный Берег',
      'Лион' => 'Овернь – Рона – Альпы',
      'Анси' => 'Овернь – Рона – Альпы',
      'Шамбери' => 'Овернь – Рона – Альпы',
      'Гренобль' => 'Овернь – Рона – Альпы',
      'Монтелимар' => 'Овернь – Рона – Альпы',
      'Клермон-Ферран' => 'Овернь – Рона – Альпы',
      'Бордо' => 'Новая Аквитания',
      'Биарриц' => 'Новая Аквитания',
      'Сарла' => 'Новая Аквитания',
      'Коньяк' => 'Новая Аквитания',
      'Пуатье' => 'Новая Аквитания',
      'Ля Рошель' => 'Новая Аквитания',
      'Перигор' => 'Новая Аквитания',
      'Тулуза' => 'Окситания',
      'Монпелье' => 'Окситания',
      'Перпиньян' => 'Окситания',
      'Рокамадур' => 'Окситания',
      'Ним' => 'Окситания',
      'Альби' => 'Окситания',
      'Страсбург' => 'Гранд-Эст',
      'Реймс' => 'Гранд-Эст',
      'Мюлуз' => 'Гранд-Эст',
      'Дижон' => 'Бургундия – Франш-Конте',
      'Бон' => 'Бургундия – Франш-Конте',
      'Аяччо' => 'Корсика',
      'Бастия' => 'Корсика',
      'Кальви' => 'Корсика',
      'Нант' => 'Земли Луары',
      'Ля Боль' => 'Земли Луары',
      'Руан' => 'Нормандия',
      'Довиль' => 'Нормандия',
      'Ле Мон-Сен-Мишель' => 'Нормандия',
      'Живерни' => 'Нормандия',
      'Тур' => 'Центр – Долина Луары',
      'Бурж' => 'Центр – Долина Луары',
      'Шартр' => 'Центр – Долина Луары',
      'Ренн' => 'Бретань',
      'Сен-Мало' => 'Бретань',
      'Киберон' => 'Бретань',
    ],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [
      '/по программе/iu',
    ],
  ],
  'gbr' => [
    'legacy_id' => 222,
    'country_slug' => 'velikobritaniya',
    'default_region' => null,
    'cities' => [
      'Лондон' => 'Лондон',
      'Хэмптон-Корт' => 'Лондон',
      'Эдинбург' => 'Шотландия',
      'Глазго' => 'Шотландия',
      'Сент Эндрюс' => 'Шотландия',
      'Белфаст' => 'Северная Ирландия',
      'Графство Антрим' => 'Северная Ирландия',
      'Лондондерри' => 'Северная Ирландия',
      'Эннискиллен' => 'Северная Ирландия',
      'Данганнон' => 'Северная Ирландия',
      'Даунпатрик' => 'Северная Ирландия',
      'Ньютаунардс' => 'Северная Ирландия',
      'Арма' => 'Северная Ирландия',
      'Бушмилс' => 'Северная Ирландия',
      'Сент Хелиер' => 'Нормандские острова',
      'Сент Питер Порт' => 'Нормандские острова',
      'Сент Мартин' => 'Нормандские острова',
      'Плейнмонт' => 'Нормандские острова',
      'Бат' => 'Юг Англии',
      'Стоунхедж' => 'Юг Англии',
      'Оксфорд' => 'Оксфордшир',
      'Виндзор' => 'Юг Англии',
      'Брайтон' => 'Юго-восточная Англия',
      'Кардифф' => 'Уэльс',
      'Конви' => 'Уэльс',
      'Карлион' => 'Уэльс',
      'Монмут' => 'Уэльс',
      'Лландудно' => 'Уэльс',
      'Карнарвон' => 'Уэльс',
      'Бомарис' => 'Уэльс',
      'Велшпул' => 'Уэльс',
      'Кембридж' => 'Восточная Англия',
      'Винчестер' => 'Юг Англии',
      'Котсволд' => 'Юг Англии',
      'Кент' => 'Юго-восточная Англия',
      'Стратфорд-на-Эйвоне' => 'Западный Мидлендс',
      'Ворвик' => 'Западный Мидлендс',
    ],
    'subtype_regions' => [
      'Шотландия' => 'Шотландия',
      'Уэльс' => 'Уэльс',
      'Северная Ирландия' => 'Северная Ирландия',
      'Остров Джерси' => 'Нормандские острова',
      'Остров Гернси' => 'Нормандские острова',
    ],
    'ignore_cities' => [
      'п-о. Пелешац',
    ],
    'skip_title_patterns' => [],
  ],
  'geo' => [
    'legacy_id' => 48963319,
    'country_slug' => 'gruziya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'grc' => [
    'legacy_id' => 29,
    'country_slug' => 'grecziya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'hrv' => [
    'legacy_id' => 48963301,
    'country_slug' => 'hovatiya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'hun' => [
    'legacy_id' => 48963311,
    'country_slug' => 'vengriya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'idn' => [
    'legacy_id' => 6221,
    'country_slug' => 'indoneziya',
    'default_region' => null,
    'cities' => [
      'о. Бали' => [
        'region' => 'Бали',
        'resort' => null,
      ],
      'о. Ява' => [
        'region' => 'Ява',
        'resort' => null,
      ],
    ],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [
      '/по программе/iu',
    ],
  ],
  'irl' => [
    'legacy_id' => 10535,
    'country_slug' => 'irlandiya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'ita' => [
    'legacy_id' => 80,
    'country_slug' => 'italiya',
    'default_region' => null,
    'cities' => [
      'Рим' => 'Лацио',
      'Террачина' => 'Лацио',
      'о. Искья' => 'Неаполь',
      'Неаполь' => 'Неаполь',
      'Казерта' => 'Неаполь',
      'Милан' => 'Ломбардия',
      'Ловере' => 'Ломбардия',
      'Бергамо' => 'Ломбардия',
      'Флоренция' => 'Тоскана',
      'Пиза' => 'Тоскана',
      'Ареццо' => 'Тоскана',
      'Сансеполькро' => 'Тоскана',
      'Кьянчано Терме' => 'Тоскана',
      'Сан Джиминьяно' => 'Тоскана',
      'Сиена' => 'Тоскана',
      'Венеция' => 'Венето',
      'Абано-Терме' => 'Венето',
      'Азоло' => 'Венето',
      'Падуя' => 'Венето',
      'Верона' => 'Венето',
      'Турин' => 'Пьемонт',
      'Нейве' => 'Пьемонт',
      'Римини' => 'Эмилия-Романья',
      'Болонья' => 'Эмилия-Романья',
      'Парма' => 'Эмилия-Романья',
      'Генуя' => 'Лигурия',
      'Телларо' => 'Лигурия',
      'Бари' => 'Апулия',
      'Монтекатини-Терме' => [
        'region' => 'Тоскана',
        'resort' => 'Монтекатини',
      ],
      'Сардиния' => [
        'region' => 'Сардиния',
        'resort' => null,
      ],
    ],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [
      '/по программе/iu',
    ],
  ],
  'jpn' => [
    'legacy_id' => 81081,
    'country_slug' => 'yaponiya',
    'default_region' => null,
    'cities' => [
      'Токио' => 'Токио',
      'Нарита' => 'Канто',
      'Йокогама' => 'Канто',
      'Камакура' => 'Канто',
      'Хаконэ' => 'Канто',
      'Кавагоэ' => 'Канто',
      'Никко' => 'Канто',
      'Киото' => 'Кансай',
      'Осака' => 'Кансай',
      'Кобе' => 'Кансай',
      'Нара' => 'Кансай',
      'Вакаяма' => 'Кансай',
      'Нагано' => 'Тюбу',
      'Мацумото' => 'Тюбу',
      'Сиракава' => 'Тюбу',
      'Канадзава' => 'Тюбу',
      'Ниигата' => 'Тюбу',
      'Окаяма' => 'Тюгоку',
      'Хиросима' => 'Тюгоку',
      'Кайкэ' => 'Тюгоку',
      'Фукуока' => 'Кюсю',
      'Саппоро' => 'Хоккайдо',
      'Хоккайдо' => 'Хоккайдо',
      'Наха' => 'Окинава',
      'Окинава' => 'Окинава',
      'По программе' => [
        'region' => null,
        'resort' => null,
      ],
    ],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'kor' => [
    'legacy_id' => 48963341,
    'country_slug' => 'yuzhnaya-koreya',
    'default_region' => null,
    'cities' => [
      'Сеул' => 'Северо-Запад Южной Кореи',
      'Инчхон' => 'Северо-Запад Южной Кореи',
      'Пусан' => 'Юго-Восток Южной Кореи',
      'Тэгу' => 'Юго-Восток Южной Кореи',
      'Кванджу' => 'Юго-Запад Южной Кореи',
      'Чеджу' => 'Остров Чеджу',
      'По программе' => [
        'region' => null,
        'resort' => null,
      ],
    ],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [
      '/по программе/iu',
    ],
  ],
  'mus' => [
    'legacy_id' => 233,
    'country_slug' => 'mavrikij',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'nld' => [
    'legacy_id' => 1,
    'country_slug' => 'niderlandy',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'prt' => [
    'legacy_id' => 22,
    'country_slug' => 'portugaliya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'rus' => [
    'legacy_id' => 460,
    'country_slug' => 'rossiya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'sgp' => [
    'legacy_id' => 665,
    'country_slug' => 'singapur',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'srb' => [
    'legacy_id' => 48963328,
    'country_slug' => 'serbia',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'svn' => [
    'legacy_id' => 48963340,
    'country_slug' => 'sloveniya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'syc' => [
    'legacy_id' => 340,
    'country_slug' => 'sejshely',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'tha' => [
    'legacy_id' => 53,
    'country_slug' => 'tailand',
    'default_region' => null,
    'cities' => [
      'Бангкок' => 'Бангкок',
      'Канчанабури' => 'Центральный Таиланд',
      'Пхукет' => 'Пхукет',
      'Самуи' => 'Самуи',
      'Сурат Тхани' => 'Южный Таиланд',
      'Чиангмай' => 'Северный Таиланд',
      'Чанг Рай' => 'Северный Таиланд',
    ],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [
      '/^(депозит|доплата|оплата счета|пакет |переписка|регистрационн|трансфер на|услуги дополнительные|отель и сервис]/iu',
      '/^москва-/iu',
      '/по программе/iu',
    ],
  ],
  'tur' => [
    'legacy_id' => 86,
    'country_slug' => 'turcziya',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'uzb' => [
    'legacy_id' => 48963321,
    'country_slug' => 'uzbekistan',
    'default_region' => null,
    'cities' => [],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [],
  ],
  'vnm' => [
    'legacy_id' => 48963331,
    'country_slug' => 'vetnam',
    'default_region' => null,
    'cities' => [
      'Ханой' => 'Север Вьетнама',
      'Хошимин' => 'Юг Вьетнама',
      'По программе' => [
        'region' => null,
        'resort' => null,
      ],
    ],
    'subtype_regions' => [],
    'ignore_cities' => [],
    'skip_title_patterns' => [
      '/по программе/iu',
    ],
  ],
];
