<?php

add_action('acf/init', function () {
  if (!function_exists('acf_add_local_field_group')) {
    return;
  }

  acf_add_local_field_group([
    'key' => 'group_bsimice_page',
    'title' => 'Лендинг MICE',
    'fields' => [
      [
        'key' => 'field_bsimice_tab_hero',
        'label' => 'Hero',
        'type' => 'tab',
      ],
      [
        'key' => 'field_bsimice_hero_bg',
        'label' => 'Фон hero',
        'name' => 'bsimice_hero_bg',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'medium',
        'library' => 'all',
      ],
      [
        'key' => 'field_bsimice_hero_title',
        'label' => 'Заголовок',
        'name' => 'bsimice_hero_title',
        'type' => 'text',
      ],
      [
        'key' => 'field_bsimice_hero_subtitle',
        'label' => 'Подзаголовок',
        'name' => 'bsimice_hero_subtitle',
        'type' => 'textarea',
        'rows' => 3,
        'new_lines' => 'br',
      ],
      [
        'key' => 'field_bsimice_tab_plates',
        'label' => 'Плашки под hero',
        'type' => 'tab',
      ],
      [
        'key' => 'field_bsimice_plates',
        'label' => 'Тексты плашек',
        'name' => 'bsimice_plates',
        'type' => 'repeater',
        'layout' => 'block',
        'button_label' => 'Добавить плашку',
        'sub_fields' => [
          [
            'key' => 'field_bsimice_plate_text',
            'label' => 'Текст',
            'name' => 'text',
            'type' => 'textarea',
            'rows' => 4,
            'new_lines' => 'br',
          ],
        ],
      ],
      [
        'key' => 'field_bsimice_tab_about',
        'label' => 'Блок «Что такое MICE»',
        'type' => 'tab',
      ],
      [
        'key' => 'field_bsimice_about_heading',
        'label' => 'Заголовок',
        'name' => 'bsimice_about_heading',
        'type' => 'text',
      ],
      [
        'key' => 'field_bsimice_about_subtitle',
        'label' => 'Подзаголовок',
        'name' => 'bsimice_about_subtitle',
        'type' => 'textarea',
        'rows' => 3,
        'new_lines' => 'br',
      ],
      [
        'key' => 'field_bsimice_about_items',
        'label' => 'Пункты M I C E',
        'name' => 'bsimice_about_items',
        'type' => 'repeater',
        'layout' => 'row',
        'button_label' => 'Добавить пункт',
        'sub_fields' => [
          [
            'key' => 'field_bsimice_about_letter',
            'label' => 'Буква (первая, в акценте)',
            'name' => 'letter',
            'type' => 'text',
            'maxlength' => 2,
            'wrapper' => ['width' => '15'],
          ],
          [
            'key' => 'field_bsimice_about_title_rest',
            'label' => 'Остаток заголовка (напр. eetings)',
            'name' => 'title_rest',
            'type' => 'text',
            'wrapper' => ['width' => '35'],
          ],
          [
            'key' => 'field_bsimice_about_item_desc',
            'label' => 'Описание',
            'name' => 'description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'br',
            'wrapper' => ['width' => '50'],
          ],
        ],
      ],
      [
        'key' => 'field_bsimice_tab_prove',
        'label' => 'Блок «Опыт / цифры»',
        'type' => 'tab',
      ],
      [
        'key' => 'field_bsimice_prove_heading',
        'label' => 'Заголовок',
        'name' => 'bsimice_prove_heading',
        'type' => 'text',
      ],
      [
        'key' => 'field_bsimice_prove_paragraphs',
        'label' => 'Абзацы',
        'name' => 'bsimice_prove_paragraphs',
        'type' => 'repeater',
        'layout' => 'block',
        'button_label' => 'Добавить абзац',
        'sub_fields' => [
          [
            'key' => 'field_bsimice_prove_p_text',
            'label' => 'Текст',
            'name' => 'text',
            'type' => 'textarea',
            'rows' => 4,
            'new_lines' => 'br',
          ],
        ],
      ],
      [
        'key' => 'field_bsimice_prove_image',
        'label' => 'Изображение справа',
        'name' => 'bsimice_prove_image',
        'type' => 'image',
        'return_format' => 'array',
        'preview_size' => 'medium',
        'library' => 'all',
      ],
      [
        'key' => 'field_bsimice_stats',
        'label' => 'Статистика (карточки)',
        'name' => 'bsimice_stats',
        'type' => 'repeater',
        'layout' => 'row',
        'button_label' => 'Добавить показатель',
        'sub_fields' => [
          [
            'key' => 'field_bsimice_stat_title',
            'label' => 'Крупный заголовок',
            'name' => 'title',
            'type' => 'text',
            'wrapper' => ['width' => '33'],
          ],
          [
            'key' => 'field_bsimice_stat_text',
            'label' => 'Подпись',
            'name' => 'text',
            'type' => 'text',
            'wrapper' => ['width' => '33'],
          ],
          [
            'key' => 'field_bsimice_stat_bg',
            'label' => 'Фоновая крупная надпись',
            'name' => 'bg_label',
            'type' => 'text',
            'wrapper' => ['width' => '34'],
          ],
        ],
      ],
      [
        'key' => 'field_bsimice_tab_services',
        'label' => 'Услуги и гарантии',
        'type' => 'tab',
      ],
      [
        'key' => 'field_bsimice_services_heading',
        'label' => 'Заголовок секции услуг',
        'name' => 'bsimice_services_heading',
        'type' => 'text',
      ],
      [
        'key' => 'field_bsimice_services',
        'label' => 'Услуги',
        'name' => 'bsimice_services',
        'type' => 'repeater',
        'layout' => 'block',
        'button_label' => 'Добавить услугу',
        'sub_fields' => [
          [
            'key' => 'field_bsimice_service_icon',
            'label' => 'Иконка (необязательно, иначе стандартная)',
            'name' => 'icon',
            'type' => 'image',
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'wrapper' => ['width' => '25'],
          ],
          [
            'key' => 'field_bsimice_service_title',
            'label' => 'Название',
            'name' => 'title',
            'type' => 'text',
            'wrapper' => ['width' => '35'],
          ],
          [
            'key' => 'field_bsimice_service_desc',
            'label' => 'Описание',
            'name' => 'description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'br',
            'wrapper' => ['width' => '40'],
          ],
        ],
      ],
      [
        'key' => 'field_bsimice_guarantees',
        'label' => 'Гарантии (2 колонки)',
        'name' => 'bsimice_guarantees',
        'type' => 'repeater',
        'layout' => 'block',
        'max' => 4,
        'button_label' => 'Добавить блок',
        'sub_fields' => [
          [
            'key' => 'field_bsimice_guarantee_title',
            'label' => 'Заголовок',
            'name' => 'title',
            'type' => 'text',
          ],
          [
            'key' => 'field_bsimice_guarantee_text',
            'label' => 'Текст',
            'name' => 'text',
            'type' => 'textarea',
            'rows' => 4,
            'new_lines' => 'br',
          ],
        ],
      ],
      [
        'key' => 'field_bsimice_tab_reviews',
        'label' => 'Отзывы',
        'type' => 'tab',
      ],
      [
        'key' => 'field_bsimice_reviews_heading',
        'label' => 'Заголовок секции',
        'name' => 'bsimice_reviews_heading',
        'type' => 'text',
      ],
      [
        'key' => 'field_bsimice_reviews',
        'label' => 'Слайды отзывов',
        'name' => 'bsimice_reviews',
        'type' => 'repeater',
        'layout' => 'block',
        'button_label' => 'Добавить отзыв',
        'sub_fields' => [
          [
            'key' => 'field_bsimice_review_quote',
            'label' => 'Текст',
            'name' => 'quote',
            'type' => 'textarea',
            'rows' => 5,
            'new_lines' => 'br',
          ],
          [
            'key' => 'field_bsimice_review_author',
            'label' => 'Имя',
            'name' => 'author_name',
            'type' => 'text',
            'wrapper' => ['width' => '50'],
          ],
          [
            'key' => 'field_bsimice_review_role',
            'label' => 'Должность / компания',
            'name' => 'author_title',
            'type' => 'text',
            'wrapper' => ['width' => '50'],
          ],
        ],
      ],
    ],
    'location' => [
      [
        [
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-bsimice.php',
        ],
      ],
    ],
  ]);
});
